import type { Metadata } from "next";
import localFont from "next/font/local";
import { cn } from "./lib/utils";
import "./styles/globals.css";
import { Navbar } from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const satoshi = localFont({
  src: "./fonts/Satoshi-Regular.woff2",
  variable: "--font-satoshi",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-[#0F0F0F] text-white font-sans antialiased select-none",
          satoshi.variable
        )}
      >
        <Navbar />

        {children}

        <Footer />
        
      </body>
    </html>
  );
}
